services:
  - type: web
    name: symfony-app
    env: php
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php bin/console cache:clear && php-fpm"
    envVars:
      - key: APP_ENV
        value: production
    disk:
      name: persistent-data
      mountPath: /var/www/html/var
